config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get '/', to: redirect('/top/index')

  get 'top/index'

  resources :incomes, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :outcomes, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :budgets, only: [:new, :create]
  get 'income_items/new', to: 'income_items#new'
  post 'income_items/create', to: 'income_items#create'

  get 'outcome_items/new', to: 'outcome_items#new'
  post 'outcome_items/create', to: 'outcome_items#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :outcome_item
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :income_item

  def self.search(start_date, end_date)
    if end_date.empty?
      where('date >= ?', start_date)
    elsif start_date.empty?
      where('date <= ?', end_date)
    elsif start_date && end_date
      where(date: start_date..end_date)
    end
  end
  
  scope :this_month, -> {
    where(date: Time.now.all_month).order(date: "DESC")
  }
end

app/models/income_item.rb
class IncomeItem < ApplicationRecord
  has_many :incomes
end

app/models/outcome.rb
class Outcome < ApplicationRecord
  belongs_to :outcome_item

  def self.search(start_date, end_date)
    if end_date.empty?
      where('date >= ?', start_date)
    elsif start_date.empty?
      where('date <= ?', end_date)
    elsif start_date && end_date
      where(date: start_date..end_date)
    end
  end
  
  scope :this_month, -> {
    where(date: Time.now.all_month).order(date: "DESC")
  }
end

app/models/outcome_item.rb
class OutcomeItem < ApplicationRecord
  has_many :outcomes
  has_many :budgets
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  validates :email, presence: true,
                    uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/}

  validates :password,
            length: {minimum: 8, message: "は8文字以上で入力してください"},
            format: { with: /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)(?=.*?[!-\/:-@\[-`{-~])[!-~]+\z/,
                      message: "は半角英小文字・大文字・数字・記号を用いて作成し、それぞれ1文字以上使用してください" }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  def new
    @budget = Budget.new
  end

  def create
    @budget = Budget.new(budgets_params)
    if @budget.save
      redirect_to top_index_path
    else
      render action: "new"
    end
  end

  private

  def budgets_params
    params.require(:budget).permit(:budget, :begining, :ending, :outcome_item_id)
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController

  def index
    @start_date = params[:start_date]
    @end_date   = params[:end_date]
    if @start_date || @end_date
      @incomes = Income.search(@start_date, @end_date)
    else
      @incomes = Income.this_month
    end
    @sum = @incomes.sum(:amounts)
  end

  def new
    @income = Income.new
  end

  def create
    @income = Income.new(incomes_params)
    if @income.save
      redirect_to top_index_path
    else
      render :new
    end
  end

  def edit
    @income = Income.find(params[:id])
  end

  def update
    @income = Income.find(params[:id])
    if @income.update(incomes_params)
      redirect_to incomes_path,
        flash: { confirm: '更新が完了しました'}
    else
      render action: "edit"
    end
  end

  def destroy
    @income = Income.find(params[:id])
    @income.destroy
    redirect_to incomes_path
  end

  private
  
  def incomes_params
    params.require(:income).permit(:id, :date, :amounts, :income_item_id, :note).merge(user_id: current_user.id)
  end

end

app/controllers/outcomes_controller.rb
class OutcomesController < ApplicationController

  def index
    @start_date = params[:start_date]
    @end_date   = params[:end_date]
    if @start_date || @end_date
      @outcomes = Outcome.search(@start_date, @end_date)
    else
      @outcomes = Outcome.this_month
    end
    @sum = @outcomes.sum(:amounts)

  end

  def new
    @outcome = Outcome.new
  end

  def create
    @outcome = Outcome.new(outcomes_params)
    if @outcome.save
      redirect_to top_index_path
    else
      render :new
    end
  end

  def edit
    @outcome = Outcome.find(params[:id])
  end

  def update
    @outcome = Outcome.find(params[:id])
    if @outcome.update(outcomes_params)
      redirect_to outcomes_path,
        flash: { confirm: '更新が完了しました'}
    else
      render action: "edit"
    end
  end

  def destroy
    @outcome = Outcome.find(params[:id])
    @outcome.destroy
    redirect_to outcomes_path
  end

  private

  def outcomes_params
    params.require(:outcome).permit(:id, :date, :amounts, :outcome_item_id, :note).merge(user_id: current_user.id)
  end  


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    @mail = params[:session][:email]
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to top_index_path
    else
      flash[:alert] = 'メールアドレスかパスワードに誤りがあります。'
      render action: 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :login_check
  def index
  end

  private
  
  def login_check
    unless logged_in?
      flash[:alert] = 'ログインしてください'
      redirect_to login_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username,:email,:password,:password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/income_items_helper.rb
module IncomeItemsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/outcome_items_helper.rb
module OutcomeItemsHelper
end

app/helpers/outcomes_helper.rb
module OutcomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
   #ブラウザからのHTTPリクエストのset-Cookieヘッダーに含まれるsessionのuser_idの値と一致するUserオブジェクトを抽出
   @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    #ログイン中＝current_userがnilでない状態
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id) #セッションからuser_idを削除
    @current_user = nil
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/budgets/new.html.erb
<h1>予算登録</h1>
  <%= form_for @budget, url: budgets_path, method: :post do |f| %>
  <div class="form_group">
    <%= f.label :begining, '開始日' %>
    <%= f.date_field :begining, class: 'date-form' %>
    <%= f.label :ending, '終了日' %>
    <%= f.date_field :ending, class: 'date-form' %>
  </div>
  <div class="form_group">
    <%= f.label :budget, '予算金額' %>
    <%= f.number_field :budget, class: 'budget-form' %>
  </div>
  <div class="form_group">
    <%= f.label :outcome_item_id, '支出費目' %>
    <%= f.select :outcome_item_id, OutcomeItem.all.map { |item| [item.title, item.id] }, class: 'outcome-item-form' %>
  </div>
  <div class="btn-block">
    <%= link_to 'トップページへ戻る', top_index_path, class: "btn" %>
    <%= f.submit '登録', class: "btn" %>
  </div>
  <% end %>

app/views/incomes/edit.html.erb
<h1>編集</h1>
  <%= form_for @income, url: income_path, method: :patch  do |f| %>
  <div class="form_group">
    <%= f.label :date, '日付' %>
    <%= f.date_field :date, value: Time.now.strftime("%Y-%m-%d"), class: 'date-form' %>
  </div>
  <div class="form_group">
    <%= f.label :amounts, '収入金額' %>
    <%= f.number_field :amounts, class: 'income-form' %>
  </div>
  <div class="form_group">
    <%= f.label :income_item_id, '収入費目' %>
    <%= f.select :income_item_id, IncomeItem.all.map { |item| [item.title, item.id] }, class: 'income-item-form' %>
  </div>
  <div class="form_group">
    <%= f.label :note, '備考メモ' %>
    <%= f.text_field :note, class: 'income-note' %>
  </div>
  <div class="btn-block">
    <%= link_to 'トップページへ戻る', top_index_path, class: "btn" %>
    <%= f.submit '編集', class: "btn" %>
  </div>
  <% end %>

app/views/incomes/index.html.erb
<h1>収入一覧</h1>
<div class="index">
  <div class="search-box">
    <%= form_tag(incomes_path, method: :get) do %>
      <div class="search-group">
        <%= label :date, '期間検索' %>
        <%= date_field_tag :start_date %>
        <%= label :date, '〜' %>
        <%= date_field_tag :end_date %>
        <%= submit_tag 'Search' %>
      </div>
    <% end %>
  </div>
  <div class="period">
    <% if @start_date || @end_date %>
    <%= "#{@start_date}" %> 〜 <%= "#{@end_date}" %> の支出一覧
    <% else %>
    <%= Date.today.month %>月の支出一覧
    <% end %>
  </div>
  <table class="incomes-index">
    <thead class="table-head">
      <tr>
        <th class="head-date">日付</th>
        <th class="head-item">収入費目</th>
        <th class="head-amount">収入金額</th>
        <th class="head-note">備考</th>
        <th class="head-edit"></th>
        <th class="head-delete"></th>
      </tr>
    </thead>
    <tbody class="table-body">
      <% @incomes.each do |income| %>
      <tr>
        <th class="table-date"><%= income.date %></th>
        <th class="table-item"><%= income.income_item.title %></th>
        <th class="table-amount"><%= income.amounts %>円</th>
        <th class="table-note"><%= income.note %></th>
        <th class="table-edit">
        <%= link_to edit_income_path(income.id) do %>
          <i class="material-icons">edit</i>
        <% end %>
        </th>
        <th class="table-delete"><%= link_to income_path(income.id), method: :delete, data: {confirm: "本当に削除してもよろしいでしょうか"} do %>
          <i class="material-icons">delete</i>
        <% end %>
        </th>
      </tr>
      <% end %>
      <tr>
        <th>当月の合計収入</th>
        <th></th>
        <th><%= @sum %>円</th>
      </tr>
    </tbody>
  </table>
</div>

<%= link_to 'トップページに戻る', top_index_path %>

app/views/incomes/new.html.erb
<h1>収入登録</h1>
  <%= form_for @income, url:incomes_path, method: :post  do |f| %>
  <div class="form_group">
    <%= f.label :date, '日付' %>
    <%= f.date_field :date, value: Time.now.strftime("%Y-%m-%d"), class: 'date-form' %>
  </div>
  <div class="form_group">
    <%= f.label :amounts, '収入金額' %>
    <%= f.number_field :amounts, class: 'income-form' %>
  </div>
  <div class="form_group">
    <%= f.label :income_item_id, '収入費目' %>
    <%= f.select :income_item_id, IncomeItem.all.map { |item| [item.title, item.id] }, class: 'income-item-form' %>
  </div>
  <div class="form_group">
    <%= f.label :note, '備考メモ' %>
    <%= f.text_field :note, class: 'income-note' %>
  </div>
  <div class="btn-block">
    <%= link_to 'トップページへ戻る', top_index_path, class: "btn" %>
    <%= f.submit '登録', class: "btn" %>
  </div>
  <% end %>

app/views/outcomes/edit.html.erb
<h1>編集</h1>
  <%= form_for @outcome, url: outcome_path, method: :patch  do |f| %>
  <div class="form_group">
    <%= f.label :date, '日付' %>
    <%= f.date_field :date, value: Time.now.strftime("%Y-%m-%d"), class: 'date-form' %>
  </div>
  <div class="form_group">
    <%= f.label :amounts, '支出金額' %>
    <%= f.number_field :amounts, class: 'outcome-form' %>
  </div>
  <div class="form_group">
    <%= f.label :outcome_item_id, '支出費目' %>
    <%= f.select :outcome_item_id, OutcomeItem.all.map { |item| [item.title, item.id] }, class: 'outcome-item-form' %>
  </div>
  <div class="form_group">
    <%= f.label :note, '備考メモ' %>
    <%= f.text_field :note, class: 'outcome-note' %>
  </div>
  <div class="btn-block">
    <%= link_to 'トップページへ戻る', top_index_path, class: "btn" %>
    <%= f.submit '編集', class: "btn" %>
  </div>
  <% end %>

app/views/outcomes/index.html.erb
<h1>支出一覧</h1>
<div class="index">
  <div class="search">
    <div class="search-box">
      <%= form_tag(outcomes_path, method: :get) do %>
        <div class="search-group">
          <%= label :date, '期間検索' %>
          <%= date_field_tag :start_date %>
          <%= label :date, '〜' %>
          <%= date_field_tag :end_date %>
          <%= submit_tag 'Search' %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="period">
    <% if @start_date || @end_date %>
    <%= "#{@start_date}" %> 〜 <%= "#{@end_date}" %> の支出一覧
    <% else %>
    <%= Date.today.month %>月の支出一覧
    <% end %>
  </div>
  <table class="outcomes-index">
    <thead class="table-head">
      <tr>
        <th class="head-date">日付</th>
        <th class="head-item">支出費目</th>
        <th class="head-amount">支出金額</th>
        <th class="head-note">備考</th>
        <th class="head-edit"></th>
        <th class="head-delete"></th>
      </tr>
    </thead>
    <tbody class="table-body">
      <% @outcomes.each do |outcome| %>
      <tr>
        <th class="table-date"><%= outcome.date %></th>
        <th class="table-item"><%= outcome.outcome_item.title %></th>
        <th class="table-amount"><%= outcome.amounts %>円</th>
        <th class="table-note"><%= outcome.note %></th>
        <th class="table-edit">
        <%= link_to edit_outcome_path(outcome.id) do %>
          <i class="material-icons">edit</i>
        <% end %>
        </th>
        <th class="table-delete"><%= link_to outcome_path(outcome.id), method: :delete, data: {confirm: "本当に削除してもよろしいでしょうか"} do %>
          <i class="material-icons">delete</i>
        <% end %>
        </th>
      </tr>
      <% end %>
      <tr>
        <th>今月の合計支出</th>
        <th></th>
        <th><%= @sum %>円</th>
      </tr>
    </tbody>
  </table>
</div>

<%= link_to 'トップページに戻る', top_index_path %>

app/views/outcomes/new.html.erb
<h1>支出登録</h1>
  <%= form_for @outcome, url: outcomes_create_path do |f| %>
  <div class="form_group">
    <%= f.label :date, '日付' %>
    <%= f.date_field :date, value: Time.now.strftime("%Y-%m-%d"), class: 'date-form' %>
  </div>
  <div class="form_group">
    <%= f.label :amounts, '支出金額' %>
    <%= f.number_field :amounts, class: 'outcome-form' %>
  </div>
  <div class="form_group">
    <%= f.label :outcome_item_id, '支出費目' %>
    <%= f.select :outcome_item_id, OutcomeItem.all.map { |item| [item.title, item.id] }, class: 'outcome-item-form' %>
  </div>
  <div class="form_group">
    <%= f.label :note, '備考メモ' %>
    <%= f.text_field :note, class: 'income-note' %>
  </div>
  <div class="btn-block">
    <%= link_to 'トップページへ戻る', top_index_path, class: "btn" %>
    <%= f.submit '登録', class: "btn" %>
  </div>
  <% end %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>
<%= form_for @user, url: signup_path, method: :post do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
  <div class="form-group">
    <%= f.label :username, 'ユーザー名' %>
    <%= f.text_field :username, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（確認）' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit '作成', class: 'btn btn-primary' %>
<% end %>
<%= link_to 'ログイン画面に戻る', login_path, class: "btn" %>